# name: Deploy Files

# on:
#   push:
#     branches:
#       - master
#   # Enables manually triggering of Workflow with file synchronization option
#   workflow_dispatch:
#     inputs:
#       sync:
#         description: 'File synchronization'
#         required: true
#         default: 'delta'

# jobs:
#   deploy-master:
#     name: 'master branch'
#     if: ${{ github.ref == 'refs/heads/master' }}
#     runs-on: ubuntu-latest
#     timeout-minutes: 30
#     steps:
#       - name: 'Checkout'
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - name: 'Deploy'
#         uses: milanmk/actions-file-deployer@master
#         with:
#           remote-protocol: 'ftp'
#           remote-host: 'ftp.blaciris.com'
#           remote-port: '20'
#           remote-user: '${{ secrets.ftp_username }}'
#           remote-password: '${{ secrets.ftp_password }}'
#           # ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
#           remote-path: '/public_html/blaciris/'
on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.5.0

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.blaciris.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/blaciris/
          port: 20
